Fix `IllegalStateException` while building a WebFlux response (#2613)
Motivation:

Received a report of the following stack trace:

    java.lang.IllegalStateException: :status header does not exist.
        at com.linecorp.armeria.common.DefaultResponseHeadersBuilder.build(DefaultResponseHeadersBuilder.java:50)
        at com.linecorp.armeria.spring.web.reactive.ArmeriaServerHttpResponse.lambda$write$3(ArmeriaServerHttpResponse.java:186)

Modifications:

- Always set the default status when `:status` header is missing.

Result:

- No more `IllegalStateException` while building a WebFlux response.